apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: node-red
  chart:
    spec:
      chart: ./node-red/charts
  values:
    controller:
      image:
        repository: nodered/node-red
        tag: "latest"
      replicaCount: 2